services:
  neo4j_db:
    image: neo4j:5.26
    container_name: neo4j_db
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j1234
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/init.sh:/tmp/init.sh
    entrypoint: ["bash", "/tmp/init.sh"]
